// Mocks generated by Mockito 5.4.0 from annotations
// in tugas_finite_state/test/api/food_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tugas_finite_state/api/foods_api.dart' as _i2;
import 'package:tugas_finite_state/model/foods_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FoodsAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodsAPI extends _i1.Mock implements _i2.FoodsAPI {
  MockFoodsAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Foods>> getFoods() => (super.noSuchMethod(
        Invocation.method(
          #getFoods,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Foods>>.value(<_i4.Foods>[]),
      ) as _i3.Future<List<_i4.Foods>>);
}
